// Program to create littlefs image comprising of input files/dirs
//
// Bandhav Veluri
// 03-07-2019

#include <dramfs/dramfs_util.h>
#include <littlefs/bd/lfs_bd.h>
#include <littlefs/lfs.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// Main file system struct
lfs_t lfs;

// LFS configuration
struct lfs_config lfs_cfg = {
    // block device operations: lfs_bd.h
    .read = lfs_read,
    .prog = lfs_prog,
    .erase = lfs_erase,
    .sync = lfs_sync,
};

// Pointer to filesystem memory
// lfs_bd uses this allocation as block device
uint8_t *lfs_ptr;

int main(int argc, char *argv[]) {
  int read_size;
  int prog_size;
  int block_size;
  int block_count;
  int lookahead;

  if (argc < 3) {
    printf(
        "Usage: dramfs_mklfs <block_size> <block_count> [input "
        "file(s)/dir(s)]\n");
    return -1;
  }

  read_size = 32;
  prog_size = 32;
  lookahead = 32;
  block_size = atoi(argv[1]);
  block_count = atoi(argv[2]);

  //+------------------------------------------------------
  //| Allocate memory for building Little FS image
  //+------------------------------------------------------

  // memory allocation for lfs
  lfs_ptr = (uint8_t *)malloc(block_size * block_count);

  // configure the size
  lfs_cfg.read_size = read_size;
  lfs_cfg.prog_size = prog_size;
  lfs_cfg.block_size = block_size;
  lfs_cfg.block_count = block_count;
  lfs_cfg.lookahead = lookahead;

  // format the fs
  if (lfs_format(&lfs, &lfs_cfg) < 0) {
    printf("LFS format error\n");
    return -1;
  }

  // mount the file system
  if (lfs_mount(&lfs, &lfs_cfg) < 0) {
    printf("LFS mount error\n");
    return -1;
  }

  //+-------------------------------------------------------
  //| Copy input files/dirs to LFS image
  //+-------------------------------------------------------

  for (int i = 3; i < argc; i++) {
    if (lfs_cp(argv[i], &lfs) < 0) return -1;
  }

  // Unmount lfs
  if (lfs_unmount(&lfs) < 0) {
    printf("LFS unmounting error\n");
    return -1;
  }

  //+------------------------------------------------------
  //| Print the LFS image as a C array
  //+------------------------------------------------------

  printf("// Newlib File System Initialization\n");
  printf("//\n");
  printf("// Autogenerated by dramfs_mkfs utility\n");
  printf("\n");
  printf("#include <sys/types.h>\n");
  printf("#include <littlefs/lfs.h>\n");
  printf("#include <littlefs/bd/lfs_bd.h>\n");
  printf("#include <dramfs/dramfs_fdtable.h>\n");
  printf("\n");

  printf(
      "// LFS configuration\n"
      "struct lfs_config dramfs_fs_cfg = {\n"
      "    // block device operations: lfs_bd.h\n"
      "    .read  = lfs_read,\n"
      "    .prog  = lfs_prog,\n"
      "    .erase = lfs_erase,\n"
      "    .sync  = lfs_sync,\n"
      "\n"
      "    // block device default configuration\n"
      "    .read_size   = %d,\n"
      "    .prog_size   = %d,\n"
      "    .block_size  = %d,\n"
      "    .block_count = %d,\n"
      "    .lookahead   = %d\n"
      "};\n\n",
      read_size, prog_size, block_size, block_count, lookahead);

  printf("uint8_t lfs_mem[] = {");

  // dump fs memory to stdout in C array format
  for (int i = 0; i < block_size * block_count; i++) {
    if (i % block_size == 0) {
      putchar('\n');
    }

    printf("0x%0x", lfs_ptr[i]);

    if (i != (block_size * block_count) - 1) putchar(',');

    putchar('\n');
  }

  printf("};\n");

  printf("// Initial FD table\n");
  printf("dramfs_fd_entry_t lfs_fdtable[DRAMFS_MAX_FDS] = {");
  printf("\t[0] = { .used = 1 }, ");
  printf("\t[1] = { .used = 1 }, ");
  printf("\t[2] = { .used = 1 }, ");
  printf("};\n");

  printf("// Internal littlefs pointers\n");
  printf("uint8_t *lfs_ptr = lfs_mem;\n");
  printf("dramfs_fd_entry_t *dramfs_fdtable = lfs_fdtable;\n");

  return 0;
}
