#ifndef DRAMFS_FS_H
#define DRAMFS_FS_H

#include <littlefs/lfs.h>

// File system memory pointer defined by littlefs BD
extern uint8_t *lfs_ptr;

// Toplevel filesystem struct
extern lfs_t dramfs_fs;

// File system configuration structure
// Initalized externally and can be generated by dramfs_mklfs
extern struct lfs_config dramfs_fs_cfg;

// LFS init routine: Should be called before calling main
int dramfs_fs_init(void);

#endif  // DRAMFS_FS_H
